/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ask_reginald;

import net.dv8tion.jda.api.AccountType;
import net.dv8tion.jda.api.JDABuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        JDABuilder builder = JDABuilder.createDefault("TOKENVAL");
    }
}
