/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.ask_reginald;

import net.dv8tion.jda.core.AccountType;
import net.dv8tion.jda.core.JDABuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    JDABuilder builder = new JDABuilder(AccountType.BOT);

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
